Feature v0.14.6 daemon restart
gravitl/netmaker pull request #1382
Opened 2022-07-12 09:40 UTC by mattkasun

replace calls to systemctl restart netclient (and other variants) with SIGHUP signal

2022-07-12 09:43 UTC, mattkasun commented
Testing:
run client on all os
execute functions that generate client restart (pull, join, leave,  UI node changes)
  look for recieved reset/restarting daemon in log file with no errors

2022-07-12 12:52 UTC, 0xdcarns requested changes

2022-07-12 12:52 UTC, 0xdcarns commented on netclient/ncutils/pid.go
> +const PIDFILE = "/var/run/netclient.pid"
will this account for a windows path..?

2022-07-12 18:25 UTC, mattkasun commented on netclient/ncutils/pid.go
> +const PIDFILE = "/var/run/netclient.pid"
added check for windows

2022-07-13 03:01 UTC, theguy951357 commented
I have clients going into error. 
If I do  netclient pull without specifying a network, I get an error in the journalctl: 
Jul 13 01:44:44 egressQA systemd[1]: netclient.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 13 01:44:44 egressQA systemd[1]: netclient.service: Failed with result 'exit-code'.
Jul 13 01:45:55 fedoraQA netclient[590006]: [netclient] 2022-07-13 01:45:55 checking for netclient updates...
Jul 13 01:45:55 fedoraQA netclient[590006]: [netclient] 2022-07-13 01:45:55 schema of network daemon-lite is out of date and cannot be updated
if I do  netclient pull and specify the network, the daemon shuts down and I have to manually start it back up.

2022-07-13 15:33 UTC, mattkasun commented
reverted to handling restarts the old way for windows.

still an issue with negative waitgroups when doing pull without specifying network

2022-07-13 19:36 UTC, mattkasun commented
gui build failure due to ??out of date apt mirror at azure?? for runner.

2022-07-15 11:33 UTC, afeiszli approved these changes

2022-07-15 14:21 UTC, 0xdcarns approved these changes

2022-07-15 14:21 UTC, merged