Add field to /api/nodes/wg-net/<network id>/creategateway for enabling/disabling NAT
gravitl/netmaker pull request #1399
Opened 2022-07-19 11:06 UTC by Exchizz

Hi,

This PR adds a field to `/api/nodes/wg-net/<network id>/creategateway` for enabling/disabling NAT for egress gateways.

Example body of a POST request:
```
{
  "ranges": [
    "1.2.3.0/24"
  ],
  "interface": "eth0",
  "natEnabled": "yes"
}
```

If "NatEnabled" is left out, it will default to "yes" hence work as before this PR.
If set to "no", it will not create the iptable rules for adding/deleting the iptables MASQUERADE rule.

I have not added any tests, let me know if you want me to.

EDIT: Tests added

\Mathias

2022-07-19 11:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker?pullRequest=1399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker?pullRequest=1399) before we can accept your contribution.<br/><hr/>**Mathias Neerup** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker?pullRequest=1399) it.</sub>

2022-07-19 15:08 UTC, 0xdcarns requested changes

2022-07-19 15:10 UTC, 0xdcarns commented
A test to ensure the code doesn't affect previous behavior would be nice to have. 

i.e. ensure by default, it is enabled

2022-07-19 19:37 UTC, Exchizz commented on models/structs.go
> +	NatEnabled  bool     `josn:"natEnabled" bson:"natEnabled"`
Fixed

2022-07-20 11:09 UTC, Exchizz commented
> A test to ensure the code doesn't affect previous behavior would be nice to have.
> 
> i.e. ensure by default, it is enabled

I've added three tests.
1. tests if "-J MASQUERADE" is present in postUp/postDown if NatEnabled is "yes"
2. tests if "-J MASQUERADE" is not present in postUp/PostDown if NatEnabled is "no"
3. tests if "-J MASQUERADE" is present in postUp/postdown id NatEnabled is leftout from the POST request when creating an Egress Gateway.

2022-07-20 20:10 UTC, mattkasun approved these changes

2022-07-20 20:42 UTC, theguy951357 commented
@Exchizz when NAT is off, I cannot ping the VPC on the egress.

2022-07-21 07:34 UTC, Exchizz commented
> @Exchizz when NAT is off, I cannot ping the VPC on the egress.

One thing that come to my mind is, if you try to ping a VM in the VPC from a node in wireguard, you need to add a route to the VM in your VPC, so that it can route back the reply to the wireguard network. This is not needed when NAT is enabled :)

If that doesn't solve the problem, I would need a description of your setup so I can see if I can reproduce the error you're experiencing.

2022-07-22 18:36 UTC, merged