Bugfix v0.14.7 relays
gravitl/netmaker pull request #1425
Opened 2022-07-27 10:27 UTC by mattkasun

2022-07-27 13:11 UTC, 0xdcarns requested changes

2022-07-27 13:23 UTC, 0xdcarns commented on logic/peers.go
> +			log.Println("ERROR RETRIEVING EXTERNAL PEERS", err)
or remove

2022-07-28 13:07 UTC, 0xdcarns approved these changes

2022-07-31 01:35 UTC, theguy951357 commented
ingress behind relay is working, but an egress behind the relay is giving a destination host unreachable

2022-08-01 06:41 UTC, abhishek9686 approved these changes

2022-08-01 19:37 UTC, merged