Bugfix v0.14.7 apple data path
gravitl/netmaker pull request #1442
Opened 2022-08-03 15:56 UTC by theguy951357

changed MAC_APP_DATA_PATH to /Library/Application\ Support

2022-08-04 12:58 UTC, 0xdcarns requested changes

2022-08-04 12:58 UTC, 0xdcarns commented on netclient/ncutils/netclientutils.go
> +const MAC_APP_DATA_PATH = "/Library/Application\\ Support/Netclient"
does the "\\\ " not result in "\ " in the path..?

2022-08-19 13:41 UTC, 0xdcarns approved these changes

2022-08-19 14:55 UTC, mattkasun approved these changes

2022-08-19 14:55 UTC, merged