Feature v0.14.7 translateiftablestonftables
gravitl/netmaker pull request #1449
Opened 2022-08-08 03:18 UTC by cameronts

Add support for nftables firewall on Linux.

2022-08-08 15:12 UTC, cameronts commented
Sanity checks:

Run with iptables on all clients (the default)
See what PostUp and PostDown are in the UI for the ingress node 
	Before it is made an ingress node
In Netmaker UI
	On node’s command line (iptables)
	Make it an ingress node
	After it is made an ingress node
In Netmaker UI
	On node’s command line (iptables)
	Stop having it be an ingress node
	After it is no longer an ingress node
In Netmaker UI
	On node’s command line (iptables)
	Run with nft (apt install nftables, confirm installed by using nft list ruleset)
	On ingress node
	On another client node (in case commands are ending up on the non-ingress clients when running nft) (more of a “control” as it’s unlikely; just to be sure it’s not happening aka a negative test)
	See what PostUp and PostDown are in the UI for the ingress node 
		Before it is made an ingress node
			In Netmaker UI
			On node’s command line (iptables)
			On node’s command line (nft)
		Make it an ingress node
		After it is made an ingress node
			In Netmaker UI
			On node’s command line (iptables)
			On node’s command line (nft) 
Make it an egress node too
	See what the PostUp and PostDown commands are


If the nft rules are in place (shown by nft list ruleset)
	Create an ext client
	Connect the ext client (some other machine) to the ingress node
	Test pings and note what works to the various other nodes

2022-08-08 16:40 UTC, 0xdcarns approved these changes

2022-08-08 19:53 UTC, mattkasun commented on logic/util.go
> +	"github.com/gravitl/netmaker/database"
order of imports

2022-08-08 20:00 UTC, mattkasun requested changes
order of file imports

2022-08-08 23:43 UTC, theguy951357 commented
pass

2022-08-09 11:26 UTC, mattkasun approved these changes

2022-08-09 13:06 UTC, merged