Fix: createExtClient()
gravitl/netmaker pull request #1453
Opened 2022-08-09 08:51 UTC by DolevBaron

The clientid supplied in the API call got discarded without ever being used, so createExtClient() could never be used with a custom client-id (until now).
I simply set the matching attribute before passing it to logic.CreateExtClient(), as otherwise it will always receive a blank ClientID & generate one on its own

2022-08-09 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker?pullRequest=1453) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker?pullRequest=1453) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker?pullRequest=1453) it.</sub>

2022-08-12 12:15 UTC, mattkasun requested changes

2022-08-30 11:54 UTC, afeiszli commented
@DolevBaron the PR will not work as written because ClientID is not in the input params for creating an ext client. This will require more work in order to merge. Did you test?

2022-08-31 09:30 UTC, k4s0 commented
I have crated a new PR with the working code for this request #1499

2022-09-02 14:16 UTC, mattkasun commented
superseded by #1499

2022-09-02 14:16 UTC, closed without merging