Feature v0.14.9 node disconnect
gravitl/netmaker pull request #1468
Opened 2022-08-19 16:35 UTC by 0xdcarns

2022-08-19 16:45 UTC, 0xdcarns commented
Added command to connect or disconnect. run with `netclient <disconnect|connect> -n network`
Test: 
- Setup dev netmaker server
- Connect a client normally
- Run disconnect command, see that no WG interface get's created and ensure it doesn't get created after checkin
- Run connect command, see that WG interface is created and ensure it stays created after checkin

Needs: Add to GUI if it works

2022-08-19 17:42 UTC, mattkasun requested changes
with the changes to ApplyXXXConf a slight refactor could eliminate all the RemoveXXXConf functions.  just call ApplyXXXConf with isConnected = false

2022-08-19 17:42 UTC, mattkasun commented on netclient/wireguard/common.go
> +
if syncconf check is removed the corresponding func arg should be removed and all calls to InitWireguard updated.

2022-08-19 17:42 UTC, mattkasun commented on netclient/wireguard/unix.go
> +// SyncWGQuickConf - formats config file and runs sync command - DEPRECATED
delete

2022-08-19 17:49 UTC, afeiszli approved these changes

2022-08-19 19:42 UTC, mattkasun requested changes

2022-08-19 19:42 UTC, mattkasun commented on netclient/wireguard/common.go
> -		err = InitWireguard(&cfg.Node, privkey, peers, false)
with this change if statement is no longer requiec

2022-08-22 13:11 UTC, abhishek9686 approved these changes

2022-08-24 03:39 UTC, theguy951357 approved these changes
This is a pass, but I wanted to note that the journal shows logs that are expected from a disconnected client but a user might think is an error. example: Aug 24 03:14:17 egressQA netclient[3005]: [netclient] 2022-08-24 03:14:17 [localport.go-26] GetLocalListenPort(): failed to parse interface nm-disconnect
Aug 24 03:14:17 egressQA netclient[3005]: [netclient] 2022-08-24 03:14:17 [localport.go-38] UpdateLocalListenPort(): network: disconnect error encountered checking local listen port:  nm-disconnect file does not exist

2022-08-25 11:40 UTC, mattkasun approved these changes

2022-08-30 11:47 UTC, afeiszli commented
Should we go ahead and merge this for 0.15.1?

2022-08-30 15:15 UTC, merged