IPv6 support for gateways
gravitl/netmaker pull request #1509
Opened 2022-09-02 15:14 UTC by mattkasun

2022-09-02 18:00 UTC, afeiszli approved these changes

2022-09-03 12:08 UTC, 0xdcarns approved these changes

2022-09-06 03:41 UTC, 0xdcarns approved these changes

2022-09-06 12:53 UTC, afeiszli requested changes
There is a significant issue using ipv6 gateways on the netmaker server running in docker right now. It wont work until we sort this out.

2022-09-06 21:03 UTC, afeiszli approved these changes

2022-09-06 21:03 UTC, merged