ee check
gravitl/netmaker pull request #1596
Opened 2022-09-22 17:02 UTC by mattkasun

To test:  verify no "collecting metrics" in netclient logs when connected to non ee server

2022-09-22 17:48 UTC, afeiszli approved these changes

2022-09-22 18:02 UTC, 0xdcarns commented
in servercfg/serverconf.go:92, the GetServerInfo func does not return/set if it is indeed in ee mode or not. In order to do this, you'll need the same logic from controllers/server.go:92-95

2022-09-22 18:03 UTC, 0xdcarns requested changes

2022-09-22 18:03 UTC, 0xdcarns commented on models/structs.go
> +	Is_EE       bool   `yaml:"isee"`
see comment in PR

2022-09-22 19:02 UTC, mattkasun commented on models/structs.go
> +	Is_EE       bool   `yaml:"isee"`
moved IS_EE var to servercfg.

2022-09-23 13:03 UTC, 0xdcarns approved these changes

2022-09-23 19:29 UTC, merged