fix workflow
gravitl/netmaker pull request #1644
Opened 2022-10-09 15:51 UTC by afeiszli

2022-10-10 20:43 UTC, mattkasun requested changes

2022-10-10 20:43 UTC, mattkasun commented on .github/workflows/publish-netclient-docker.yml
> +      #   name: Build armv7l and export to Docker
Remove instead of commenting out

2022-10-11 16:20 UTC, afeiszli commented on .github/workflows/publish-netclient-docker.yml
> +      #   name: Build armv7l and export to Docker
removed

2022-10-11 16:21 UTC, mattkasun approved these changes

2022-10-11 20:43 UTC, merged