Feature v0.17.0 compose scripts
gravitl/netmaker pull request #1772
Opened 2022-11-28 18:58 UTC by afeiszli

2022-11-28 18:59 UTC, afeiszli commented
To test nm-quick and nm-quick-interactive, use this branch: https://github.com/gravitl/netmaker/tree/test_v0.17.0_compose (uses branch name and test image for downloads. This branch will have correct branch names / images only when in production)

2022-11-28 19:11 UTC, mattkasun requested changes

2022-11-28 19:11 UTC, mattkasun commented on compose/docker-compose.yml
> +    image: gravitl/netmaker:testing
this should be v0.17.0

2022-11-28 19:11 UTC, mattkasun commented on compose/docker-compose.yml
> +    image: gravitl/netmaker-ui:testing
v0.17.0

2022-11-28 19:11 UTC, mattkasun commented on docker/mosquitto.conf
> +allow_anonymous true
this should remain as false

2022-11-29 16:34 UTC, afeiszli commented on docker/mosquitto.conf
> +allow_anonymous true
resolved

2022-11-29 16:43 UTC, mattkasun approved these changes

2022-11-29 16:45 UTC, 0xdcarns approved these changes

2022-11-29 16:45 UTC, merged