Feature host relay
gravitl/netmaker pull request #1917
Opened 2023-01-10 17:27 UTC by abhishek9686

-> Added APIs to create/delete host relay and respective functions to support relay operations on host
-> added relay fields to host model
-> relay information in host update for proxy
-> fixed node model conversion during node update

 **YET TO REMOVE OLD CODE RELATED TO NODE RELAYS** ( will be a separate PR)

2023-01-10 19:22 UTC, mattkasun requested changes
run go mod tidy

2023-01-10 19:22 UTC, mattkasun commented on models/host.go
> +	IsRelayed        bool             `json:"isrelayed" bson:"isrelayed" yaml:"isrelayed"`
bson tags not required

2023-01-10 19:22 UTC, mattkasun commented on models/structs.go
> +	HostID       string   `json:"host_id" bson:"host_id"`
bson tags not required

2023-01-11 15:55 UTC, 0xdcarns approved these changes

2023-01-12 09:58 UTC, abhishek9686 commented
> run go mod tidy

updated go mod and sum

2023-01-12 14:56 UTC, 0xdcarns approved these changes

2023-01-12 15:03 UTC, 0xdcarns approved these changes

2023-01-12 15:03 UTC, merged