remove dependencies on netclient
gravitl/netmaker pull request #1986
Opened 2023-01-27 21:25 UTC by mattkasun

2023-01-27 22:37 UTC, theguy951357 commented
netmaker-1 came back on this one 
<img width="1202" alt="Screenshot 2023-01-27 at 5 36 38 PM" src="https://user-images.githubusercontent.com/18285922/215219428-8e8f7ed5-c176-443d-89bb-775c0c789ddc.png">

2023-01-30 12:31 UTC, abhishek9686 reviewed
left comments on related PR https://github.com/gravitl/netclient/pull/164

2023-01-30 13:35 UTC, theguy951357 commented
will wait on changes

2023-01-30 18:26 UTC, theguy951357 approved these changes
everything functions as before

2023-01-31 13:52 UTC, 0xdcarns requested changes

2023-01-31 13:52 UTC, 0xdcarns commented on metrics/metrics.go
> +const MetricCollectionInterval = time.Second * 25
I'm sure it was missing before, but public variable missing comment

2023-01-31 13:52 UTC, 0xdcarns commented on models/proxy.go
> +// Metric - struct for metric data
incorrect comment

2023-02-01 03:37 UTC, 0xdcarns approved these changes

2023-02-01 12:57 UTC, abhishek9686 approved these changes

2023-02-01 13:28 UTC, merged