Gra 1088 dns updates
gravitl/netmaker pull request #2001
Opened 2023-02-06 20:39 UTC by mattkasun

2023-02-14 16:39 UTC, 0xdcarns requested changes

2023-02-14 16:39 UTC, 0xdcarns commented on mq/publishers.go
> +	clients, err := logic.GetNetworkExtClients(newnode.Network)
from 217-250, could probably be another function to getAllDNS or something

2023-02-14 16:39 UTC, 0xdcarns commented on mq/publishers.go
> +// PublishDeleteExtClient publish dns update to delete extclient entry
incorrect Comment

2023-02-14 16:39 UTC, 0xdcarns commented on mq/publishers.go
> +// PublishExtClientUpdate publishes dns update for extclient name change
incorrect comment

2023-02-14 18:53 UTC, theguy951357 commented
advised to wait.

2023-02-14 19:30 UTC, 0xdcarns approved these changes

2023-02-14 21:41 UTC, afeiszli approved these changes

2023-02-15 16:41 UTC, theguy951357 approved these changes
followed instructions on GRA-1088
all steps pass

2023-02-15 17:55 UTC, merged