updates to zombie processing
gravitl/netmaker pull request #2026
Opened 2023-02-13 19:53 UTC by mattkasun

2023-02-13 20:42 UTC, 0xdcarns requested changes

2023-02-13 20:42 UTC, 0xdcarns commented on logic/zombie.go
> +			zombies = append(zombies, node.ID)
may need to synchronize these writes

2023-02-13 20:42 UTC, 0xdcarns commented on logic/zombie.go
> +			zombies = append(zombies, node.ID)
to both slices

2023-02-13 20:56 UTC, theguy951357 approved these changes
works pending changes

2023-02-14 13:32 UTC, 0xdcarns approved these changes

2023-02-14 19:48 UTC, theguy951357 approved these changes
testing steps done in GRA-1085
pass

2023-02-14 19:50 UTC, merged