Gra 1191 legacy nodes
gravitl/netmaker pull request #2049
Opened 2023-02-17 10:50 UTC by mattkasun

updated migration function

2023-02-17 11:30 UTC, alphadose approved these changes

2023-02-17 12:12 UTC, Aceix approved these changes

2023-02-17 17:09 UTC, theguy951357 approved these changes
pass

2023-02-24 20:06 UTC, theguy951357 reviewed
changes needed are noted in GRA-1191

2023-03-06 20:17 UTC, theguy951357 commented
testing fails on windows.
testing notes and log and config files in gra-1191 ticket.

2023-03-09 13:37 UTC, 0xdcarns requested changes

2023-03-09 13:37 UTC, 0xdcarns commented on controllers/migrate.go
> +	pretty.Println(data.JoinData)
pretty print needed?

2023-03-09 14:05 UTC, theguy951357 approved these changes
pr passes pending changes addressed.

2023-03-09 15:27 UTC, mattkasun commented on controllers/migrate.go
> +	pretty.Println(data.JoinData)
removed debug log

2023-03-09 17:44 UTC, 0xdcarns approved these changes

2023-03-09 17:44 UTC, merged