Gra 1198 enrollment keys
gravitl/netmaker pull request #2050
Opened 2023-02-17 17:05 UTC by 0xdcarns

Do not merge till post 0.18.1
Testing steps:

- [ ] Ensure you can create a enrollment keys only with admin privileges
- `curl -X POST -H "Authorization: Bearer <admin JWT>" -d '{"expiration":0,"uses_remaining":10,"networks":["networktoJoin1","network2"],"unlimited":false,"tags":[]}' https://<mydomain.com>/api/v1/enrollment-keys`
  `curl -H "Authorization: Bearer <admin JWT>" https://mydomain.com/api/v1/enrollment-keys | jq`
uses_remaining = how many uses are on it
expiration is set with unix time
unlimited indicates unlimited use one of those must be set, otherwise should fail

- [] Ensure you can get enrollment keys only with admin privileges
- `curl -H "Authorization: Bearer <admin JWT>" https://<mydomain.com>/api/v1/enrollment-keys | jq`
- [] Ensure you can delete an enrollment key only with admin privilege
- `curl -X DELETE -H "Authorization: Bearer <admin JWT>" https://<mydomain.com>/api/v1/enrollment-keys/<keyValue>`

- [] Check PR https://github.com/gravitl/netclient/pull/223 for netclient usability

2023-02-21 16:33 UTC, 0xdcarns commented on controllers/enrollmentkeys.go
> +	r.HandleFunc("/api/v1/enrollment-keys", logic.SecurityCheck(true, http.HandlerFunc(createEnrollmentKey))).Methods(http.MethodPost)
I'm doing it for this one

2023-02-22 12:39 UTC, Aceix requested changes

2023-02-23 13:58 UTC, 0xdcarns commented on models/enrollment_key.go
> +func (k *EnrollmentKey) IsValid() bool {
that's not correct

2023-02-24 13:00 UTC, Aceix approved these changes

2023-02-24 13:31 UTC, mattkasun approved these changes

2023-02-24 16:22 UTC, afeiszli requested changes
Should be able to use more than one enrollment key after joining a server, to join additional networks.

2023-02-28 14:26 UTC, merged

2023-02-28 14:26 UTC, theguy951357 approved these changes
checkmarks on pr pass
critical pr checklist 100%
pass