Story/gra 1252
gravitl/netmaker pull request #2067
Opened 2023-02-23 23:53 UTC by afeiszli

## Describe your changes

This modifies the nm-quick script to do the following:
1. Adds a "-a" flag, which will run "auto install" with default options. No prompts will be used.
2. Installs the netclient into the docker-compose, makes it a default host and an ingress gw

This also makes a small change to nm-upgrade to replace some faulty logic, and adds an example netclient docker-compose file to the compose folder.

## Provide Issue ticket number if applicable/not in title

GRA-1252 (this is one part of a bigger ticket)

## Provide testing steps

1. Run "./nm-quick.sh -a" on a fresh linux machine
2. See that netmaker successfully installs, and there is a healthy netclient running

## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [x] Netmaker is awesome.

2023-02-24 13:53 UTC, mattkasun reviewed
how is netclient going to work in a container?
the netclient.sh script tries to join using a token and if it fails it exits

2023-02-27 05:30 UTC, theguy951357 commented
will wait on changes.

2023-02-27 06:19 UTC, theguy951357 commented
I did test this one. the script runs well. the netmaker-1 node is connected.
I can ping the netmaker-1 and the netmaker-1 can ping other peers.
ingress and egress are not reachable when created in netmaker-1.
netmaker-1 can reach an ingress and egress that are created on other peers.

can test again after comments addressed and merge conflict fixed

2023-03-01 13:01 UTC, afeiszli commented
The iptables commands in docker netclient are not working properly with the host. I've moved it back to a host-level install for now, which appears to be working fine. Will re-attempt a docker installation in next release once we've sorted out issues with iptables in docker.

2023-03-02 20:57 UTC, afeiszli commented
@theguy951357 can we get a retest on this please?

2023-03-02 21:13 UTC, theguy951357 commented
ok testing now.

2023-03-02 21:51 UTC, theguy951357 approved these changes
netmaker server is up and running
netclient is up and running
pr checklist 100%

2023-03-07 19:09 UTC, afeiszli commented
@mattkasun removed container portion

2023-03-09 10:37 UTC, mattkasun requested changes

2023-03-09 10:37 UTC, mattkasun commented on compose/docker-compose.netclient.yml
> +    depends_on:
why would this depend on netmaker?

2023-03-09 21:57 UTC, afeiszli commented on compose/docker-compose.netclient.yml
> +    depends_on:
fixed

2023-03-09 21:58 UTC, mattkasun approved these changes

2023-03-14 18:45 UTC, merged