Gra 1328 0.18.3 develop
gravitl/netmaker pull request #2094
Opened 2023-03-04 19:37 UTC by theguy951357

## Describe your changes
update develop to 0.18.3

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
none needed

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [x] My unit tests pass locally.
- [x] Netmaker is awesome.

2023-03-04 19:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker?pullRequest=2094) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker?pullRequest=2094) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: 0xdcarns<br/>:white_check_mark: mattkasun<br/>:white_check_mark: alphadose<br/>:white_check_mark: walkerwmanuel<br/>:white_check_mark: theguy951357<br/>:x: dependabot[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker?pullRequest=2094) it.</sub>

2023-03-06 15:32 UTC, 0xdcarns approved these changes

2023-03-06 17:03 UTC, mattkasun requested changes
release.mf

2023-03-07 13:13 UTC, theguy951357 commented
good to go

2023-03-07 13:45 UTC, merged