add json format output alternative to tables
gravitl/netmaker pull request #2098
Opened 2023-03-06 06:40 UTC by alphadose

## Describe your changes
Add JSON format output alternative to tables for automation

## Provide Issue ticket number if applicable/not in title
https://toil.kitemaker.co/cQARgD-Gravitl/Nk7Fgo-Main_Board/items/1322

## Provide testing steps
Add the `-o json` flag or the `--output json` flag to any list command

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-03-06 10:51 UTC, mattkasun requested changes

2023-03-06 10:51 UTC, mattkasun commented on cli/cmd/commons/globals.go
> +var OutputFormat string
This should be private vice public

2023-03-06 10:53 UTC, mattkasun approved these changes

2023-03-06 18:50 UTC, 0xdcarns approved these changes

2023-03-07 13:44 UTC, abhishek9686 approved these changes

2023-03-07 13:48 UTC, theguy951357 approved these changes
-o commands with list shows a json output
critical list 100%

2023-03-07 13:49 UTC, merged