GRA-1342: added DNS publish when host add nodes
gravitl/netmaker pull request #2113
Opened 2023-03-13 20:32 UTC by 0xdcarns

## Describe your changes

- [ ] Fixed issue where DNS updates not sent whenever Host registers initially to networks

## Provide Issue ticket number if applicable/not in title
title.
## Provide testing steps

- [ ] after registration with networks, ensure DNS is populated for said networks

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-03-13 20:37 UTC, afeiszli approved these changes

2023-03-13 21:40 UTC, mattkasun requested changes

2023-03-13 21:40 UTC, mattkasun commented on mq/handlers.go
> +		dns.Address = node.Address6.IP.String()
should be node.Address not node.Address6

2023-03-15 04:19 UTC, theguy951357 approved these changes
dns entries show up on a register
critical checklist 100%

2023-03-15 12:47 UTC, abhishek9686 approved these changes

2023-03-15 12:52 UTC, merged