GRA-1369 - added logic for ext client ACLs
gravitl/netmaker pull request #2119
Opened 2023-03-14 16:30 UTC by 0xdcarns

## Describe your changes
- Added  logic for ext client ACLs
- Fixed bug where deleting client would not remove from ingress node

## Provide Issue ticket number if applicable/not in title
title.
## Provide testing steps
Easiest way without UI:
- [ ] Join 1 node
- [ ] Set it's default ACL to deny
- [ ] Join another (ingress node) to network
- [ ] Ensure ACLs are functioning/no peers
- [ ] Set other to ingress and create a client
- [ ] Apply client conf to working WG machine
- [ ] Allow via UI ACLs for first node to talk to ingress node
- [ ] Ensure you can ping the ingress node, but not the ext client (should get destination unreachable or timeout)

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-03-14 16:37 UTC, abhishek9686 requested changes

2023-03-15 08:44 UTC, abhishek9686 approved these changes

2023-03-15 12:14 UTC, afeiszli approved these changes

2023-03-15 16:23 UTC, theguy951357 approved these changes
checklist passes
critical checklist passes

2023-03-15 17:19 UTC, merged