Add host level auto update setting with default true
gravitl/netmaker pull request #2133
Opened 2023-03-20 12:22 UTC by alphadose

## Describe your changes
Add host level auto update setting with default true

## Provide Issue ticket number if applicable/not in title
https://toil.kitemaker.co/cQARgD-Gravitl/Nk7Fgo-Main_Board/items/1374

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-03-20 15:05 UTC, Aceix approved these changes
Looks good but "NETCLIENT_AUTO_UPDATE" sounds more specific

2023-03-20 15:07 UTC, 0xdcarns requested changes

2023-03-21 10:20 UTC, mattkasun approved these changes

2023-03-21 12:35 UTC, alphadose commented on servercfg/serverconf.go
> +	return os.Getenv("NETCLIENT_AUTO_UPDATE") != "disabled"
@abhishek9686 done

2023-03-21 18:52 UTC, theguy951357 commented
I need testing steps for this one please

2023-04-18 20:59 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-04-19 13:40 UTC, merged