refactor key updates on host basis vice node
gravitl/netmaker pull request #2199
Opened 2023-04-13 19:03 UTC by mattkasun

## Describe your changes
new endpoints for host key updates
deletion of network key update endpoint

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
see GRA-1529

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-04-14 11:23 UTC, Aceix approved these changes

2023-04-15 17:14 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-04-18 02:55 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-04-19 13:20 UTC, 0xdcarns requested changes

2023-04-19 13:20 UTC, 0xdcarns commented on mq/handlers.go
> +				publish(&host, fmt.Sprintf("peers/host/%s/%s", host.ID.String(), servercfg.GetServer()), data)
servercfg.GetServer() performs a small amount of logic, should be set to variable outside of loop. `serverName := servercfg.GetServer()`

2023-04-19 13:20 UTC, 0xdcarns commented on mq/handlers.go
> +				publish(&host, fmt.Sprintf("peers/host/%s/%s", host.ID.String(), servercfg.GetServer()), data)
also resolve conflicts

2023-04-19 17:08 UTC, 0xdcarns approved these changes

2023-04-19 18:00 UTC, 0xdcarns requested changes

2023-04-19 18:00 UTC, 0xdcarns commented on controllers/network.go
> -	logic.SortNetworks(allnetworks[:])
put this back

2023-04-19 18:00 UTC, 0xdcarns commented on logic/networks.go
> -func SortNetworks(unsortedNetworks []models.Network) {
put this function back

2023-04-19 18:11 UTC, 0xdcarns approved these changes

2023-04-19 18:11 UTC, merged