GRA-1385: adapted sso to host registration
gravitl/netmaker pull request #2214
Opened 2023-04-17 21:17 UTC by 0xdcarns

## Describe your changes
- Adapted callback controllers for SSO/Basic Auth host registration
## Provide Issue ticket number if applicable/not in title
title.
## Provide testing steps

- [ ] Ensure you can register a host with a valid user via basic auth
- [ ] Ensure you can register a host with SSO
- [ ] Ensure you can register a host to a specific network `netclient register -s "api-server" -n "network-id"`
- [ ] Ensure you can register a host to all networks as an admin user `netclient register -s "api-server" -A`

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-04-17 22:43 UTC, mattkasun requested changes

2023-04-17 22:43 UTC, mattkasun commented on models/host.go
> +// Need to change mac to public key for tighter verification ?
Delete comment  -- not applicable

2023-04-17 22:59 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-04-18 12:32 UTC, abhishek9686 approved these changes

2023-04-18 12:53 UTC, mattkasun approved these changes

2023-04-18 13:30 UTC, merged