Net 83i
gravitl/netmaker pull request #2271
Opened 2023-05-05 15:07 UTC by mattkasun

## Describe your changes
add type to enrollment key

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
see Net-83

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-05-05 17:12 UTC, afeiszli approved these changes

2023-05-08 01:38 UTC, Aceix requested changes
- add type to `APIEnrollmentKey` struct and creation logic as well
- change key validity logic to use type (EnrollmentKey.IsValid)

2023-05-08 13:49 UTC, abhishek9686 requested changes

2023-05-08 13:49 UTC, abhishek9686 commented on migrate/migrate.go
> +func Run() {
missing comment

2023-05-09 14:41 UTC, TobiaszCudnik approved these changes

2023-05-10 20:21 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-05-10 21:41 UTC, merged