Extclient NET-63x
gravitl/netmaker pull request #2286
Opened 2023-05-11 17:16 UTC by mattkasun

## Describe your changes
update Extclient models with additional editable fields
add length check to extclient names
updates to create/update extclient for additional fields
updates to nmctl 

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
see NET-63x
## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-05-11 20:44 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-05-12 12:56 UTC, TobiaszCudnik approved these changes

2023-05-12 12:56 UTC, TobiaszCudnik commented on cli/cmd/ext_client/create.go
> +	allowedips  []string
`allowedIPs`?

2023-05-12 13:38 UTC, abhishek9686 requested changes

2023-05-12 13:38 UTC, abhishek9686 commented on controllers/regex_test.go
> +func TestValidName(t *testing.T) {
missing comment

2023-05-12 13:38 UTC, abhishek9686 commented on models/node.go
> +	IngressDNS          string        `json:"extclientdns" yaml:"extclientdns"`
json tag supposed to be `ingress_dns`?

2023-05-12 13:55 UTC, mattkasun commented on controllers/ext_client.go
> +	newclient, err := logic.UpdateExtClient(&oldExtClient, &update)
the same way there are now ee.logic.ext_acls.go

2023-05-12 22:08 UTC, Aceix requested changes
can you add `extclientdns` to `/${networkId}/${nodeId}/createingress`

2023-05-15 11:20 UTC, mattkasun commented
> can you add `extclientdns` to `/${networkId}/${nodeId}/createingress`
added

2023-05-15 23:34 UTC, Aceix approved these changes

2023-05-16 07:56 UTC, TobiaszCudnik approved these changes

2023-05-16 07:56 UTC, TobiaszCudnik commented on cli/cmd/ext_client/create.go
> +			ClientID:        extClientID,
Are these simply empty string assignments?

2023-05-17 03:36 UTC, afeiszli commented
Is this ready to merge?

2023-05-17 14:58 UTC, merged