NET-53 Fixed user update returns old data
gravitl/netmaker pull request #2312
Opened 2023-05-19 12:11 UTC by TobiaszCudnik

## Describe your changes

NET-53 Fixed user update returns old data

## Provide testing steps

```
$ nmctl user create --groups g1,g2,g3 --name user1 --password 123123 --networks netmaker

$ nmctl user update user1 --groups g1,g2 --networks netmaker

{
  "username": "user1",
  "password": "$2a$05$y6eRwKRnFtYR7kiccZXlCO/DuPXQg7dYNKO.jPRR.4usW.HWWplnW",
  "networks": [
    "netmaker"
  ],
  "isadmin": false,
  "groups": [
    "g1",
    "g2"
  ]
}
```

## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [x] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [x] My unit tests pass locally.
- [x] Netmaker is awesome.

2023-05-19 14:17 UTC, mattkasun requested changes

2023-05-22 10:33 UTC, TobiaszCudnik commented on controllers/user.go
> +		logger.Log(0, username,
Assignments in conditions scope new declarations and `userUpdated` is used in the outer scope. Ive re-used `userChange` and merged everything into one `if`.

2023-05-22 13:11 UTC, TobiaszCudnik commented on controllers/user.go
> +		logger.Log(0, username,
Following the code a couple of lines above it.

2023-05-22 20:35 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-05-22 21:57 UTC, merged