Net 137p - Pull requests
gravitl/netmaker pull request #2349
Opened 2023-05-29 13:15 UTC by mattkasun

## Describe your changes
update pull requests for relay refactor
## Provide Issue ticket number if applicable/not in title

## Provide testing steps
see NET-137p

2023-05-30 09:45 UTC, abhishek9686 requested changes

2023-05-30 09:45 UTC, abhishek9686 commented on logic/peers.go
> +		node, err := GetNodeByID(uuid.MustParse(nodeStr).String())
`nodeStr` is a string, why parse it again?

2023-05-30 09:45 UTC, abhishek9686 commented on logic/relay.go
> +		Host: *GetHostByNodeID(relayNode.ID.String()),
use node.HostID to get Host

2023-05-30 09:45 UTC, abhishek9686 commented on logic/peers.go
> +func GetPeerUpdateForRelay(client *models.Client, peers *[]models.Client) []wgtypes.PeerConfig {
why pointer to slice?

2023-05-30 11:20 UTC, mattkasun commented on logic/peers.go
> +							Node: peer,
single return vs double return

2023-05-30 12:41 UTC, TobiaszCudnik approved these changes

2023-05-31 02:50 UTC, abhishek9686 approved these changes

2023-05-31 11:38 UTC, merged