NET-345 memleak fix from #2399
gravitl/netmaker pull request #2404
Opened 2023-06-19 16:02 UTC by TobiaszCudnik

## Describe your changes

Extract from #2399.

## Provide testing steps

1. Start netmaker
2. Check the memory
3. Wait 24h
4. Check the memory

Result: Should be less with this PR than without it.

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-06-20 10:57 UTC, abhishek9686 requested changes

2023-06-20 10:57 UTC, abhishek9686 commented on logic/zombie.go
using a ticker would be more appropriate.
reference - https://gobyexample.com/tickers

2023-06-21 09:48 UTC, TobiaszCudnik commented on logic/zombie.go
I agree but theres no benefit in changing it now - it will work the same way, the memleak is the issue of this PR.

2023-06-21 10:01 UTC, abhishek9686 commented on logic/zombie.go
Also i don't quite understand how is `time.After(time.Hour * ZOMBIE_TIMEOUT)` causing mem leak, could you explain?

2023-06-21 10:03 UTC, abhishek9686 commented
PR should be raised against `develop`, please change the destination branch

2023-06-21 22:07 UTC, mattkasun commented on logic/zombie.go
> I agree but theres no benefit in changing it now - it will work the same way, the memleak is the issue of this PR.

The timer was added as part of this PR, so the recommendation to use ticker is valid

2023-06-28 14:55 UTC, closed without merging