nm-quick netmaker edition upgrade fix
gravitl/netmaker pull request #2440
Opened 2023-07-06 14:46 UTC by uGiFarukh

## Describe your changes
nm-quick netmaker edition upgrade fix.

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
Install Netmaker CE using the nm-quick.sh script. After that try to upgrade it to Netmaker EE by using nm-quick.sh with the "-e" flag set. For example -> sudo nm-quick.sh -e

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-07-06 16:11 UTC, theguy951357 requested changes
it is setting the image to an ee image, but is not turning prometheus and netmaker_exporter to on.

2023-07-06 18:47 UTC, theguy951357 approved these changes

2023-07-10 11:54 UTC, abhishek9686 approved these changes

2023-07-10 12:15 UTC, mattkasun approved these changes

2023-07-11 10:57 UTC, afeiszli approved these changes

2023-07-13 02:54 UTC, merged