Nm quick ee instructions update
gravitl/netmaker pull request #2441
Opened 2023-07-06 19:32 UTC by theguy951357

## Describe your changes
changed instructions for netmaker ee installation and fixed a metrics exporter and prometheus bug

## Provide Issue ticket number if applicable/not in title
NET-422
## Provide testing steps
on NET-422
## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [x] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [x] I have had my code reviewed by a peer.
- [x] My unit tests pass locally.
- [x] Netmaker is awesome.

2023-07-07 14:27 UTC, mattkasun approved these changes

2023-07-09 19:27 UTC, Aceix approved these changes

2023-07-10 11:46 UTC, abhishek9686 requested changes

2023-07-10 11:46 UTC, abhishek9686 commented on config/config.go
> +	NetmakerAccountID          string    `yaml:"netmaker_tenant_id"`
even the struct field can be changed to `NetmakerTenantID`

2023-07-11 07:34 UTC, abhishek9686 requested changes

2023-07-11 07:34 UTC, abhishek9686 commented on ee/license.go
> +	NetmakerTenantID := servercfg.GetNetmakerTenantID()
local variable shouldn't start with capital letter `NetmakerTenantID` -> `netmakerTenantID`

2023-07-11 07:34 UTC, abhishek9686 commented on servercfg/serverconf.go
> +	NetmakerTenantID := os.Getenv("NETMAKER_TENANT_ID")
`NetmakerTenantID` -> `netmakerTenantID`

2023-07-13 02:51 UTC, abhishek9686 approved these changes

2023-07-13 02:53 UTC, abhishek9686 commented
@gabrielseibel1  please make a note to update the version template in the next release before updating tenants 
in the version template change the `NETMAKER_ACCOUNT_ID` -> `NETMAKER_TENANT_ID`

2023-07-13 02:53 UTC, merged