Net 437
gravitl/netmaker pull request #2454
Opened 2023-07-13 19:59 UTC by mattkasun

add PR number to discord messages

2023-07-13 19:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker?pullRequest=2454) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker?pullRequest=2454) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: Aceix<br/>:white_check_mark: theguy951357<br/>:white_check_mark: mattkasun<br/>:white_check_mark: abhishek9686<br/>:white_check_mark: uGiFarukh<br/>:x: dependabot[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker?pullRequest=2454) it.</sub>

2023-07-13 20:27 UTC, theguy951357 approved these changes

2023-07-14 02:41 UTC, abhishek9686 requested changes

2023-07-14 02:41 UTC, abhishek9686 commented on .github/workflows/deletedroplets.yml
> +          message: " ${{ github.repository}}:${{ github.event.workflow_run.name }}:PR ${{ env.pull_request}} failed: droplets from this workflow (tag ${{ github.event.workflow_run.id }}-${{ github.ev
this is supposed to be a message for successful run
why does it say failed?

2023-07-14 15:35 UTC, abhishek9686 approved these changes

2023-07-14 15:35 UTC, merged