[NET-398] Netmaker should indicate licensing/payment issues
gravitl/netmaker pull request #2465
Opened 2023-07-25 17:32 UTC by gabrielseibel1

## Describe your changes

Now netmaker should have more verbose errors on license validation failures

## Provide testing steps

Described in kitemaker ticket

## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [x] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [x] My unit tests pass locally.
- [x] Netmaker is awesome.

2023-07-25 19:09 UTC, mattkasun requested changes
Should be using slog for new logs

2023-07-26 17:58 UTC, theguy951357 approved these changes
tested and passed

2023-07-26 18:15 UTC, mattkasun approved these changes

2023-07-26 22:58 UTC, Aceix approved these changes

2023-07-27 06:03 UTC, abhishek9686 approved these changes

2023-07-27 06:03 UTC, merged