add force flag to host/node delete
gravitl/netmaker pull request #2548
Opened 2023-08-29 11:32 UTC by mattkasun

2023-09-04 05:15 UTC, abhishek9686 requested changes

2023-09-04 05:15 UTC, abhishek9686 commented on cli/functions/host.go
> +		return request[models.ApiHost](http.MethodDelete, "/api/hosts/"+hostID+"?force=true", nil)
use the force arg value

2023-09-04 05:15 UTC, abhishek9686 commented on cli/functions/node.go
> +		return request[models.SuccessResponse](http.MethodDelete, fmt.Sprintf("/api/nodes/%s/%s/?force=true", networkName, nodeID), nil)
use the force arg value

2023-09-05 09:11 UTC, abhishek9686 approved these changes

2023-09-12 01:45 UTC, uGiFarukh approved these changes

2023-09-12 16:32 UTC, Aceix approved these changes

2023-09-13 04:40 UTC, merged