feat(NET-591): allow generic DNS entries
gravitl/netmaker pull request #2568
Opened 2023-09-11 22:47 UTC by pwilson77

## Describe your changes
Allow users to create generic DNS entries that are not tied to the network TLD. E.g. "myserver.example.com"
## Provide Issue ticket number if applicable/not in title
NET-591

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-09-11 22:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker?pullRequest=2568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker?pullRequest=2568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker?pullRequest=2568) it.</sub>

2023-09-12 05:16 UTC, abhishek9686 approved these changes

2023-09-12 10:10 UTC, mattkasun approved these changes

2023-09-12 10:12 UTC, abhishek9686 commented
@pwilson77  fix unit tests, they are failing

2023-09-12 12:00 UTC, Aceix requested changes
fix tests

2023-09-12 22:29 UTC, pwilson77 commented
> fix tests

Fixed the test failures

2023-09-13 01:51 UTC, Aceix approved these changes

2023-09-20 12:20 UTC, merged