NET-600
gravitl/netmaker pull request #2571
Opened 2023-09-12 02:01 UTC by uGiFarukh

## Describe your changes
* Extclients DNS now properly set from ingress dns value provided that the individual extclient DNS are not present. Updated DNS only applies to newly created extclients after an ingress dns update from the netmaker UI. Individual extclients DNS which are set by user will take precedence over ingress gateway dns.

## Provide Issue ticket number if applicable/not in title

## Provide testing steps
1. Create an ingress gateway with a DNS address set.
2. Create extclients using this ingress gateway.
3. Open the extclient's details page by clicking on the name.
4. This page should reflect the DNS set on the ingress gateway.
5. Change the ingress gateway dns server to a different one and create another extclient.
6. New ingress gateway dns now should be reflected on the new extclient details page.
7. Any ingress gateway dns changes should properly reflect on newly created extclients unless an extclient have dns server set through its own configuration page.

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-09-12 05:12 UTC, abhishek9686 requested changes

2023-09-12 05:12 UTC, abhishek9686 commented on controllers/ext_client.go
issue related to this ticket is totally different

2023-09-12 12:24 UTC, Aceix requested changes
i think this should be empty instead

2023-09-12 15:47 UTC, Aceix approved these changes

2023-09-13 08:32 UTC, abhishek9686 approved these changes

2023-09-18 07:58 UTC, merged