open api spec file
gravitl/netmaker pull request #2595
Opened 2023-09-19 19:51 UTC by mattkasun

swagger.yml generated by:
`swagger generate spec -t ee -o swagger.yml`

2023-09-20 00:17 UTC, Aceix approved these changes
is there a way to ignore the static checks for these lines?

2023-09-20 17:20 UTC, mattkasun commented
> is there a way to ignore the static checks for these lines?

Static checks fixed

2023-09-21 22:23 UTC, uGiFarukh approved these changes

2023-09-22 09:16 UTC, abhishek9686 requested changes

2023-10-04 06:26 UTC, abhishek9686 approved these changes

2023-10-04 06:26 UTC, merged