NET-667: force delete daemon node
gravitl/netmaker pull request #2645
Opened 2023-10-26 10:01 UTC by abhishek9686

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-10-26 11:46 UTC, mattkasun requested changes

2023-10-26 11:46 UTC, mattkasun commented on controllers/hosts.go
> +			err = logic.DeleteNodeByID(&node)
combine lines 332-333
`if err := logic.DeleteNodeByID(node); err != nil {`

2023-10-26 15:57 UTC, mattkasun approved these changes

2023-10-30 10:27 UTC, Aceix approved these changes

2023-10-31 10:34 UTC, merged