feat(NET-688): auto relaying via enrollment keys
gravitl/netmaker pull request #2647
Opened 2023-10-27 10:06 UTC by Aceix

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netmaker is awesome.

2023-10-31 10:30 UTC, abhishek9686 requested changes

2023-10-31 10:30 UTC, abhishek9686 commented on auth/host_session.go
> +			}
you should update node, after setting it as relayed here

2023-10-31 10:30 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +func updateEnrollmentKey(w http.ResponseWriter, r *http.Request) {
we shouldn't have update of enrollment key, it brings in unnecessary complexities

2023-10-31 10:30 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +	shouldOmitRelaying := r.URL.Query().Get("omitRelay") == "true"
if enrollment key has a relay attached it, it should be automatically relayed, remove query param

2023-10-31 10:30 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +func updateEnrollmentKey(w http.ResponseWriter, r *http.Request) {
user can always re-create if necessary

2023-10-31 10:30 UTC, abhishek9686 commented on pro/logic/relays.go
> +// UpdateRelayed - updates a ralay's relayed nodes, and sends updates to the relayed nodes over MQ
typo in comment `ralay's`

2023-10-31 10:59 UTC, abhishek9686 requested changes

2023-10-31 10:59 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +	if err != nil {
this will give an error if `enrollmentKeyBody.Relay` is empty string, skip parsing if `enrollmentKeyBody.Relay)` is not set

2023-10-31 10:59 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +	if err != nil {
skip parsing if enrollmentKeyBody.Relay) is not set

2023-10-31 10:59 UTC, abhishek9686 commented on controllers/enrollmentkeys.go
> +	logger.Log(2, r.Header.Get("user"), "updated enrollment key")
use slog

2023-10-31 10:59 UTC, abhishek9686 commented on logic/enrollmentkey.go
> +		nodes, err := GetAllNodes()
use `GetNodeByID`

2023-10-31 10:59 UTC, abhishek9686 commented on logic/enrollmentkey.go
> +		nodes, err := GetAllNodes()
use `GetNodeByID`

2023-11-02 05:06 UTC, abhishek9686 requested changes

2023-11-02 07:41 UTC, Aceix commented on auth/host_session.go
> +					slog.Error("failed to update node", "nodeid", relayNodeId.String())
done

2023-11-02 07:43 UTC, abhishek9686 approved these changes

2023-11-03 12:34 UTC, theguy951357 approved these changes

2023-11-03 16:33 UTC, uGiFarukh approved these changes

2023-11-04 12:28 UTC, merged